# Main CI/CD workflow for the Starfall 2D project.
name: Starfall 2D CI & Documentation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows manual runs from the GitHub Actions tab.
  workflow_dispatch:

# Grant GITHUB_TOKEN permissions for deployment.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SDL2 Dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Build Project
        run: make

      - name: Verify Build
        run: test -f build/starfall

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: starfall-linux-executable
          path: build/starfall

  # New job to deploy documentation to GitHub Pages.
  deploy-docs:
    # This job will only run if the 'build' job succeeds.
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Documentation Tools
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: make docs

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire 'docs' directory.
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
